version: '3'

services:
  nats-server:
    image: nats:alpine3.19

  client-gateway:
    image: fmyersdev/client-gateway-prod:1.0.0
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
  auth-ms:
    image: fmyersdev/auth-ms:1.0.0
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  orders-ms:
    image: fmyersdev/orders-ms:1.0.0
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  products-ms:
    image: fmyersdev/products-ms:1.0.0
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}
  # # =======================================
  # # Payments Microservice
  # # =======================================

  payments-ms:
    ports:
      - ${PAYMENTS_PORT}:${PAYMENTS_PORT}
    image: fmyersdev/payments-ms:1.0.0
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${PAYMENTS_PORT}
      - STRIPE_SECRET=${PAYMENTS_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_STRIPE_ENDPOINT_SECRET}
